title: Vaseman
public: /
parses:
    - .vaseman/.npmrc.dist
scripts:
    - rm -rf assets
    - cp .vaseman/.npmrc.dist .vaseman/.npmrc
    - yarn install --cwd .vaseman
    - cd .vaseman; yarn build
    - vaseman up -a
